# Generated by Django 4.2.5 on 2023-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_created_date_alter_todoitem_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created'),
        ),
    ]
