# Generated by Django 4.2.5 on 2023-10-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
