# Generated by Django 4.2.5 on 2023-11-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_todoitem_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCreating',
        ),
    ]
